# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/janwin443/Documents/luminary/luminary-cpp-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/janwin443/Documents/luminary/luminary-cpp-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/janwin443/Documents/luminary/luminary-cpp-main/CMakeFiles /home/janwin443/Documents/luminary/luminary-cpp-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/janwin443/Documents/luminary/luminary-cpp-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named luminary_core

# Build rule for target.
luminary_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 luminary_core
.PHONY : luminary_core

# fast build rule for target.
luminary_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary_core.dir/build.make CMakeFiles/luminary_core.dir/build
.PHONY : luminary_core/fast

#=============================================================================
# Target rules for targets named luminary

# Build rule for target.
luminary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 luminary
.PHONY : luminary

# fast build rule for target.
luminary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/build
.PHONY : luminary/fast

#=============================================================================
# Target rules for targets named ofl-cpp

# Build rule for target.
ofl-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ofl-cpp
.PHONY : ofl-cpp

# fast build rule for target.
ofl-cpp/fast:
	$(MAKE) $(MAKESILENT) -f third_party/open-fixture-language/cpp/CMakeFiles/ofl-cpp.dir/build.make third_party/open-fixture-language/cpp/CMakeFiles/ofl-cpp.dir/build
.PHONY : ofl-cpp/fast

#=============================================================================
# Target rules for targets named ofl_test

# Build rule for target.
ofl_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ofl_test
.PHONY : ofl_test

# fast build rule for target.
ofl_test/fast:
	$(MAKE) $(MAKESILENT) -f third_party/open-fixture-language/cpp/CMakeFiles/ofl_test.dir/build.make third_party/open-fixture-language/cpp/CMakeFiles/ofl_test.dir/build
.PHONY : ofl_test/fast

src/config/config.o: src/config/config.cpp.o
.PHONY : src/config/config.o

# target to build an object file
src/config/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/config/config.cpp.o
.PHONY : src/config/config.cpp.o

src/config/config.i: src/config/config.cpp.i
.PHONY : src/config/config.i

# target to preprocess a source file
src/config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/config/config.cpp.i
.PHONY : src/config/config.cpp.i

src/config/config.s: src/config/config.cpp.s
.PHONY : src/config/config.s

# target to generate assembly for a file
src/config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/config/config.cpp.s
.PHONY : src/config/config.cpp.s

src/core/engine/engine.o: src/core/engine/engine.cpp.o
.PHONY : src/core/engine/engine.o

# target to build an object file
src/core/engine/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary_core.dir/build.make CMakeFiles/luminary_core.dir/src/core/engine/engine.cpp.o
.PHONY : src/core/engine/engine.cpp.o

src/core/engine/engine.i: src/core/engine/engine.cpp.i
.PHONY : src/core/engine/engine.i

# target to preprocess a source file
src/core/engine/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary_core.dir/build.make CMakeFiles/luminary_core.dir/src/core/engine/engine.cpp.i
.PHONY : src/core/engine/engine.cpp.i

src/core/engine/engine.s: src/core/engine/engine.cpp.s
.PHONY : src/core/engine/engine.s

# target to generate assembly for a file
src/core/engine/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary_core.dir/build.make CMakeFiles/luminary_core.dir/src/core/engine/engine.cpp.s
.PHONY : src/core/engine/engine.cpp.s

src/core/patch/patch.o: src/core/patch/patch.cpp.o
.PHONY : src/core/patch/patch.o

# target to build an object file
src/core/patch/patch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/core/patch/patch.cpp.o
.PHONY : src/core/patch/patch.cpp.o

src/core/patch/patch.i: src/core/patch/patch.cpp.i
.PHONY : src/core/patch/patch.i

# target to preprocess a source file
src/core/patch/patch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/core/patch/patch.cpp.i
.PHONY : src/core/patch/patch.cpp.i

src/core/patch/patch.s: src/core/patch/patch.cpp.s
.PHONY : src/core/patch/patch.s

# target to generate assembly for a file
src/core/patch/patch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/core/patch/patch.cpp.s
.PHONY : src/core/patch/patch.cpp.s

src/core/universe/universe.o: src/core/universe/universe.cpp.o
.PHONY : src/core/universe/universe.o

# target to build an object file
src/core/universe/universe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary_core.dir/build.make CMakeFiles/luminary_core.dir/src/core/universe/universe.cpp.o
.PHONY : src/core/universe/universe.cpp.o

src/core/universe/universe.i: src/core/universe/universe.cpp.i
.PHONY : src/core/universe/universe.i

# target to preprocess a source file
src/core/universe/universe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary_core.dir/build.make CMakeFiles/luminary_core.dir/src/core/universe/universe.cpp.i
.PHONY : src/core/universe/universe.cpp.i

src/core/universe/universe.s: src/core/universe/universe.cpp.s
.PHONY : src/core/universe/universe.s

# target to generate assembly for a file
src/core/universe/universe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary_core.dir/build.make CMakeFiles/luminary_core.dir/src/core/universe/universe.cpp.s
.PHONY : src/core/universe/universe.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net/http_server.o: src/net/http_server.cpp.o
.PHONY : src/net/http_server.o

# target to build an object file
src/net/http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/http_server.cpp.o
.PHONY : src/net/http_server.cpp.o

src/net/http_server.i: src/net/http_server.cpp.i
.PHONY : src/net/http_server.i

# target to preprocess a source file
src/net/http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/http_server.cpp.i
.PHONY : src/net/http_server.cpp.i

src/net/http_server.s: src/net/http_server.cpp.s
.PHONY : src/net/http_server.s

# target to generate assembly for a file
src/net/http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/http_server.cpp.s
.PHONY : src/net/http_server.cpp.s

src/net/node_discovery.o: src/net/node_discovery.cpp.o
.PHONY : src/net/node_discovery.o

# target to build an object file
src/net/node_discovery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/node_discovery.cpp.o
.PHONY : src/net/node_discovery.cpp.o

src/net/node_discovery.i: src/net/node_discovery.cpp.i
.PHONY : src/net/node_discovery.i

# target to preprocess a source file
src/net/node_discovery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/node_discovery.cpp.i
.PHONY : src/net/node_discovery.cpp.i

src/net/node_discovery.s: src/net/node_discovery.cpp.s
.PHONY : src/net/node_discovery.s

# target to generate assembly for a file
src/net/node_discovery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/node_discovery.cpp.s
.PHONY : src/net/node_discovery.cpp.s

src/net/pin_auth.o: src/net/pin_auth.cpp.o
.PHONY : src/net/pin_auth.o

# target to build an object file
src/net/pin_auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/pin_auth.cpp.o
.PHONY : src/net/pin_auth.cpp.o

src/net/pin_auth.i: src/net/pin_auth.cpp.i
.PHONY : src/net/pin_auth.i

# target to preprocess a source file
src/net/pin_auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/pin_auth.cpp.i
.PHONY : src/net/pin_auth.cpp.i

src/net/pin_auth.s: src/net/pin_auth.cpp.s
.PHONY : src/net/pin_auth.s

# target to generate assembly for a file
src/net/pin_auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/pin_auth.cpp.s
.PHONY : src/net/pin_auth.cpp.s

src/net/socket_server.o: src/net/socket_server.cpp.o
.PHONY : src/net/socket_server.o

# target to build an object file
src/net/socket_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/socket_server.cpp.o
.PHONY : src/net/socket_server.cpp.o

src/net/socket_server.i: src/net/socket_server.cpp.i
.PHONY : src/net/socket_server.i

# target to preprocess a source file
src/net/socket_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/socket_server.cpp.i
.PHONY : src/net/socket_server.cpp.i

src/net/socket_server.s: src/net/socket_server.cpp.s
.PHONY : src/net/socket_server.s

# target to generate assembly for a file
src/net/socket_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/net/socket_server.cpp.s
.PHONY : src/net/socket_server.cpp.s

src/protocol/artnet.o: src/protocol/artnet.cpp.o
.PHONY : src/protocol/artnet.o

# target to build an object file
src/protocol/artnet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/artnet.cpp.o
.PHONY : src/protocol/artnet.cpp.o

src/protocol/artnet.i: src/protocol/artnet.cpp.i
.PHONY : src/protocol/artnet.i

# target to preprocess a source file
src/protocol/artnet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/artnet.cpp.i
.PHONY : src/protocol/artnet.cpp.i

src/protocol/artnet.s: src/protocol/artnet.cpp.s
.PHONY : src/protocol/artnet.s

# target to generate assembly for a file
src/protocol/artnet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/artnet.cpp.s
.PHONY : src/protocol/artnet.cpp.s

src/protocol/artnet_poll.o: src/protocol/artnet_poll.cpp.o
.PHONY : src/protocol/artnet_poll.o

# target to build an object file
src/protocol/artnet_poll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/artnet_poll.cpp.o
.PHONY : src/protocol/artnet_poll.cpp.o

src/protocol/artnet_poll.i: src/protocol/artnet_poll.cpp.i
.PHONY : src/protocol/artnet_poll.i

# target to preprocess a source file
src/protocol/artnet_poll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/artnet_poll.cpp.i
.PHONY : src/protocol/artnet_poll.cpp.i

src/protocol/artnet_poll.s: src/protocol/artnet_poll.cpp.s
.PHONY : src/protocol/artnet_poll.s

# target to generate assembly for a file
src/protocol/artnet_poll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/artnet_poll.cpp.s
.PHONY : src/protocol/artnet_poll.cpp.s

src/protocol/udp.o: src/protocol/udp.cpp.o
.PHONY : src/protocol/udp.o

# target to build an object file
src/protocol/udp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/udp.cpp.o
.PHONY : src/protocol/udp.cpp.o

src/protocol/udp.i: src/protocol/udp.cpp.i
.PHONY : src/protocol/udp.i

# target to preprocess a source file
src/protocol/udp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/udp.cpp.i
.PHONY : src/protocol/udp.cpp.i

src/protocol/udp.s: src/protocol/udp.cpp.s
.PHONY : src/protocol/udp.s

# target to generate assembly for a file
src/protocol/udp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luminary.dir/build.make CMakeFiles/luminary.dir/src/protocol/udp.cpp.s
.PHONY : src/protocol/udp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... luminary"
	@echo "... luminary_core"
	@echo "... ofl-cpp"
	@echo "... ofl_test"
	@echo "... src/config/config.o"
	@echo "... src/config/config.i"
	@echo "... src/config/config.s"
	@echo "... src/core/engine/engine.o"
	@echo "... src/core/engine/engine.i"
	@echo "... src/core/engine/engine.s"
	@echo "... src/core/patch/patch.o"
	@echo "... src/core/patch/patch.i"
	@echo "... src/core/patch/patch.s"
	@echo "... src/core/universe/universe.o"
	@echo "... src/core/universe/universe.i"
	@echo "... src/core/universe/universe.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/http_server.o"
	@echo "... src/net/http_server.i"
	@echo "... src/net/http_server.s"
	@echo "... src/net/node_discovery.o"
	@echo "... src/net/node_discovery.i"
	@echo "... src/net/node_discovery.s"
	@echo "... src/net/pin_auth.o"
	@echo "... src/net/pin_auth.i"
	@echo "... src/net/pin_auth.s"
	@echo "... src/net/socket_server.o"
	@echo "... src/net/socket_server.i"
	@echo "... src/net/socket_server.s"
	@echo "... src/protocol/artnet.o"
	@echo "... src/protocol/artnet.i"
	@echo "... src/protocol/artnet.s"
	@echo "... src/protocol/artnet_poll.o"
	@echo "... src/protocol/artnet_poll.i"
	@echo "... src/protocol/artnet_poll.s"
	@echo "... src/protocol/udp.o"
	@echo "... src/protocol/udp.i"
	@echo "... src/protocol/udp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

